---
- name: Work with files
  hosts: managed_hosts
  become: false

  tasks:
    - name: Create multiple directories
      file:
        path: /tmp/{{ item }}
        state: directory
        mode: '0755'
      loop:
        - test_dir1
        - test_dir2
        - test_dir3

    - name: Create files in directories
      copy:
        content: "This is {{ item }} file\n"
        dest: /tmp/{{ item }}/content.txt
      loop:
        - test_dir1
        - test_dir2
        - test_dir3

    - name: Read files (idempotent)
      slurp:
        src: /tmp/{{ item }}/content.txt
      loop:
        - test_dir1
        - test_dir2
        - test_dir3
      register: file_content

    - name: Show file contents
      debug:
        msg: "{{ item.content | b64decode }}"
      loop: "{{ file_content.results }}"

